### ISSUE TITLE
audio input TODO:

### ISSUE THREAD

**Issue by boourns** [boourns/burns-audio-wam#30]
- [x] race condition in firefox when reloading track page while initializaing
<img width="702" alt="image" src="https://user-images.githubusercontent.com/699550/162999018-c2156f2c-582b-4b10-8d66-bdbf7e0187eb.png">

- [x] if we set to track [1/2] by default and then the number of channels changes, we should search for the same combination instead of mapping to whatever is in index 3

- [x] VU meter not always updating correctly when updating the channel routing

- [x] monitor in/out/auto and follow the 'rec' signal from DAW

**Comment by boourns** [comment]
monitor on/off/autio is more interesting than I realized, when monitor is set to "off" the recording clip still receives audio (unlike muting the input), however the audio is not passed past the audio clip recorder.  Useful to lay down something while not listening to it and then play it back in context, which is often how I want to record I think.

Solutions...
- move monitor state onto the track recorder.
- maybe make it part of the recording wam extension so it can be controlled from the track page.
